/* global localDB, cajaActual, salesHistory, renderCajaView, currentUser, configStorageKey */
const { test, expect } = require('@playwright/test');
for (const flow of ['DIRECT', 'CENTRALIZED']) test('resumen y detalles de cierre local ' + flow, async ({ page }) => {
  if(flow==='CENTRALIZED') await page.setViewportSize({width:390,height:844}); await page.goto('/'); await page.locator('#loginUsername').fill('andres'); await page.locator('#loginPassword').fill('4321'); await page.locator('#loginForm button[type=submit]').click(); await expect(page.locator('#app')).toBeVisible();
  await page.locator('#navCajaBtn').click(); await page.locator('#cajaEfectivoInicialInput').fill('5000'); await page.locator('#abrirCajaBtn').click(); await expect(page.locator('#cajaAbiertaBox')).toBeVisible();
  const actor = await page.evaluate(async flow => {
    localStorage.setItem(configStorageKey, JSON.stringify({...JSON.parse(localStorage.getItem(configStorageKey)||'{}'),salesFlow:flow}));
    const values = [['Contado','cash',1000],['Crédito','credit',2000],['Contado','transfer',2000],['Contado','card',25]];
    for(const [metodo,medioPago,total] of values) { const sale = {id:Date.now()+Math.random(),business_id:cajaActual.business_id,cajaSessionId:cajaActual.id,fechaTS:Date.now(),metodo,medioPago,total,anulada:false}; salesHistory.push(sale); await localDB.sales.put(sale); }
    cajaActual.movimientos = [{tipo:'salida',monto:500,concepto:'Gasto: Alquiler'},{tipo:'salida',monto:500,concepto:'Retiro manual'},{tipo:'salida',monto:200,concepto:'Compra',referenciaCompraId:'purchase-test'},{tipo:'entrada',monto:50,concepto:'Abono',referenciaAbonoId:'payment-test'}];
    await localDB.cajaSessions.put(cajaActual); renderCajaView(); return currentUser.displayName;
  }, flow);
  await page.locator('#cerrarCajaBtn').click(); const modal = page.locator('#cierreCajaModal'); await expect(modal).toBeVisible(); await expect(modal.locator('h2')).toHaveText('Resumen de cierre de caja'); await expect(modal.locator('h2')).toBeInViewport();
  await expect(page.locator('#cajaCierreResumen')).toContainText(actor); await expect(page.locator('#cajaCierreResumen')).toContainText('Fecha y hora de apertura'); await expect(page.locator('#cajaCierreResumen')).toContainText('Fecha y hora de cierre'); await expect(page.locator('#cajaEsperadoDisplay')).toHaveText('C$ 4,850.00'); await expect(page.locator('#confirmCierreCajaBtn')).toBeDisabled(); await modal.screenshot({path:test.info().outputPath('summary.png')}); await page.keyboard.press('Shift+Tab'); await expect(modal.locator('.close-modal-btn')).toBeFocused(); await page.keyboard.press('Tab'); await expect(page.locator('#cajaEfectivoRealInput')).toBeFocused();
  await modal.locator('.close-modal-btn').click(); expect(await page.evaluate(() => cajaActual.estado)).toBe('abierta');
  await page.locator('#cerrarCajaBtn').click(); await page.locator('#cajaEfectivoRealInput').fill('4800'); await expect(page.locator('#cajaCierreDiferencia')).toContainText('C$ -50.00'); await expect(page.locator('#cajaCierreDiferencia')).toContainText('Faltante');
  await page.locator('#cajaEfectivoRealInput').fill('4900'); await expect(page.locator('#cajaCierreDiferencia')).toContainText('+C$ 50.00'); await page.locator('#confirmCierreCajaBtn').click(); await expect(modal).toBeHidden(); await page.locator('#customAlertModal .close-modal-btn').click();
  const row=page.locator('#cajaHistorialBody tr').first(); await expect(row).toContainText('C$ 4,850.00'); await row.getByRole('button',{name:'Detalles',exact:true}).click(); const details=page.locator('#detalleCierreCajaModal'); await expect(details).toBeVisible();
  for(const label of ['Ventas de contado en efectivo','Ventas de crédito','Ventas por transferencia','Ventas por tarjeta','Gastos en efectivo','Salidas manuales','Compras en efectivo','Efectivo real contado','Diferencia']) await expect(details).toContainText(label);
  await expect(details.locator('input,select,textarea')).toHaveCount(0); await details.screenshot({path:test.info().outputPath('details.png')}); await expect(details).toContainText('C$ 1,000.00'); await expect(details).toContainText('C$ 2,000.00'); await expect(details).toContainText('C$ 25.00');
  await details.locator('.close-modal-btn').click(); await page.reload(); await page.locator('#loginUsername').fill('andres'); await page.locator('#loginPassword').fill('4321'); await page.locator('#loginForm button[type=submit]').click(); await expect(page.locator('#app')).toBeVisible(); await page.locator('#navCajaBtn').click(); await page.locator('#cajaHistorialBody tr').first().getByRole('button',{name:'Detalles',exact:true}).click(); await expect(page.locator('#cajaDetalleResumen')).toContainText('C$ 4,850.00');
});
