'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomBytes, randomUUID } = require('node:crypto');
const { readConfig } = require('../../src/config/environment');
const { readAuthConfig } = require('../../src/config/auth');
const { createDatabasePool } = require('../../src/config/database');
const { createAuthRepository, rows } = require('../../src/repositories/auth');
const { createAuthService } = require('../../src/services/auth');
const { createUsersService } = require('../../src/services/users');
const { hashPassword } = require('../../src/services/passwords');
const { createApp } = require('../../src/app');
const database = process.env.POS_INTEGRATION_DATABASE;
if (!/^pos_auth_test_[a-f0-9]{24}$/.test(database || '') || database === process.env.DB_NAME) throw new Error('Use isolated runner');
const password = 'Customer-fixture-password-123!';
function client(base) {
  const jar = new Map(); let csrf;
  async function request(path, method = 'GET', body, headers = {}) {
    const response = await fetch(base + '/api' + path, { method, headers: { Cookie: [...jar].map(([key,value]) => key + '=' + value).join('; '), ...(method === 'GET' ? {} : { 'Content-Type':'application/json', 'X-CSRF-Token':csrf || '' }), ...headers }, body: method === 'GET' ? undefined : JSON.stringify(body) });
    for (const cookie of response.headers.getSetCookie()) { const pair = cookie.split(';')[0], pos = pair.indexOf('='); jar.set(pair.slice(0,pos), pair.slice(pos+1)); }
    const data = response.status === 204 ? undefined : await response.json(); if (data?.csrfToken) csrf = data.csrfToken; return { status:response.status, data };
  }
  async function login(businessId, username) { await request('/auth/csrf'); assert.equal((await request('/auth/login','POST',{businessId,username,password})).status,200); }
  return { request, login };
}
test('Fase 5.4: clientes, credito conectado, cuentas por cobrar y abonos', async t => {
  const config = readConfig(), authConfig = readAuthConfig({ CSRF_SECRET:randomBytes(32).toString('hex'), AUTH_RATE_MAX:'100' });
  const pool = createDatabasePool({ ...config.database, database, connectionLimit:20 }); t.after(() => pool.end());
  const business = String((await rows(pool,'INSERT INTO businesses (name) VALUES (?)',['Credit A'])).insertId);
  const businessOther = String((await rows(pool,'INSERT INTO businesses (name) VALUES (?)',['Credit B'])).insertId);
  const hash = await hashPassword(password);
  await rows(pool,'INSERT INTO users (business_id, username, full_name, password_hash, role) VALUES (?, ?, ?, ?, ?)',[business,'creditadmin','creditadmin',hash,'ADMIN']);
  await rows(pool,'INSERT INTO users (business_id, username, full_name, password_hash, role) VALUES (?, ?, ?, ?, ?)',[businessOther,'creditadminb','creditadminb',hash,'ADMIN']);
  const repo = createAuthRepository(pool, authConfig), auth = createAuthService(repo, authConfig);
  const server = createApp({ config, checkDatabase:async()=>{}, authentication:{ repo, auth, config:authConfig, users:createUsersService(repo) } }).listen(0,'127.0.0.1');
  await new Promise(ok => server.once('listening',ok)); t.after(() => new Promise(ok => { server.close(ok); server.closeAllConnections(); }));
  const admin = client('http://127.0.0.1:' + server.address().port); await admin.login(business,'creditadmin');
  const count = async table => Number((await rows(pool,'SELECT COUNT(*) AS n FROM ' + table + ' WHERE business_id = ?',[business]))[0].n);
  const productInput = { barcode:'C-' + randomUUID(), name:'Credit product', category:'General', cost:'8.00', marginRetail:'25', marginWholesale:'12.5', retailPrice:'10.00', wholesalePrice:'9.00', stock:'100.000', minStock:'0' };
  const productResponse = await admin.request('/products','POST',productInput); assert.equal(productResponse.status,201); const product = productResponse.data.product;
  const cashOpen = await admin.request('/cash/sessions','POST',{ operationKey:randomUUID(), openingAmount:'100.00' }); assert.equal(cashOpen.status,201); let cash;
  const newClient = (name, creditLimit = '10.00') => ({ name, phone:'555' + randomUUID().replaceAll('-','').slice(0,9), ruc:null, address:'Centro', creditLimit, creditDays:15 });
  const created = await admin.request('/clients','POST',newClient('Acme ' + randomUUID().slice(0,8))); assert.equal(created.status,201); const first = created.data.client;
  assert.equal(first.businessId,business); assert.equal(first.creditDays,15); assert.equal(first.debt,'0.00');
  const duplicate = await admin.request('/clients','POST',newClient(first.name,'50.00')); assert.equal(duplicate.status,409); assert.equal(duplicate.data.error.code,'CLIENT_DUPLICATE');
  const updated = await admin.request('/clients/' + first.id,'PATCH',{ phone:'5551002', creditLimit:'10.00', creditDays:15 }); assert.equal(updated.status,200); assert.equal(updated.data.client.phone,'5551002');
  assert.equal((await admin.request('/clients/' + first.id + '/active','PATCH',{active:false})).data.active,false);
  const creditCart = (clientId, changes = {}) => ({ items:[{productId:product.id,quantity:'1.000'}], priceType:'RETAIL', discountPercent:'0', paymentMethod:'CREDIT', ...(clientId ? {clientId} : {}), ...changes });
  assert.equal((await admin.request('/sales/quote','POST',creditCart(null))).data.error.code,'CREDIT_CLIENT_REQUIRED');
  assert.equal((await admin.request('/sales/quote','POST',creditCart(first.id))).data.error.code,'CLIENT_INACTIVE');
  await admin.request('/clients/' + first.id + '/active','PATCH',{active:true});
  const sale = async (clientId, changes = {}) => { const input = creditCart(clientId,changes), quote = await admin.request('/sales/quote','POST',input); assert.equal(quote.status,200); return admin.request('/sales','POST',{...input,operationKey:randomUUID(),quoteToken:quote.data.quote.quoteToken,cashReceived:null,detail:'Credit test'}); };
  const beforeCashMovements = await count('cash_movements'), beforeExpected = (await admin.request('/cash/current?full=true')).data.cash.expectedAmount;
  const firstSaleResponse = await sale(first.id); assert.equal(firstSaleResponse.status,201); const firstSale = firstSaleResponse.data.sale;
  assert.equal(firstSale.paymentMethod,'CREDIT'); assert.equal(firstSale.clientId,first.id); assert.equal(firstSale.cashStatus,'NOT_APPLICABLE'); assert.ok(firstSale.dueAt);
  assert.equal((await admin.request('/products/' + product.id)).data.product.stock,'99.000');
  assert.equal(await count('cash_movements'),beforeCashMovements); assert.equal((await admin.request('/cash/current?full=true')).data.cash.expectedAmount,beforeExpected);
  for (const path of ['/clients?limit=100&q='+first.id,'/sales/clients?limit=100&q='+first.id]) {
    const found=await admin.request(path);assert.equal(found.status,200);assert.ok(found.data.clients.some(item=>item.id===first.id));
  }
  assert.ok((await admin.request('/receivables?limit=100&q='+first.id)).data.receivables.some(item=>item.clientId===first.id));
  const receivableResponse = await admin.request('/receivables?limit=100'); assert.equal(receivableResponse.status,200,JSON.stringify(receivableResponse.data));
  let receivables = receivableResponse.data.receivables; let invoice = receivables.find(item => item.id === firstSale.id);
  assert.equal(invoice.status,'OPEN'); assert.equal(invoice.total,'10.00'); assert.equal(invoice.balance,'10.00'); assert.equal(invoice.paid,'0.00');
  let pay = await admin.request('/receivables/' + firstSale.id + '/payments','POST',{operationKey:randomUUID(),amount:'2.00',paymentMethod:'CASH'});
  assert.equal(pay.status,201); assert.equal(pay.data.payment.status,'POSTED'); assert.equal((await admin.request('/cash/current?full=true')).data.cash.expectedAmount,'102.00');
  assert.equal((await admin.request('/receivables/' + firstSale.id + '/payments','POST',{operationKey:randomUUID(),amount:'8.01',paymentMethod:'CASH'})).data.error.code,'PAYMENT_EXCEEDS_BALANCE');
  pay = await admin.request('/receivables/' + firstSale.id + '/payments','POST',{operationKey:randomUUID(),amount:'3.00',paymentMethod:'CARD'});
  assert.equal(pay.status,201); assert.equal(pay.data.payment.status,'PENDING'); assert.equal((await admin.request('/cash/current?full=true')).data.cash.expectedAmount,'102.00');
  receivables = (await admin.request('/receivables?limit=100')).data.receivables; invoice = receivables.find(item => item.id === firstSale.id);
  assert.equal(invoice.paid,'2.00'); assert.equal(invoice.balance,'8.00'); assert.equal(invoice.remaining,'5.00'); assert.equal(invoice.status,'PENDING_CONFIRMATION');
  assert.equal((await admin.request('/receivables/' + firstSale.id + '/payments','POST',{operationKey:randomUUID(),amount:'5.01',paymentMethod:'TRANSFER'})).data.error.code,'PAYMENT_CONFIRMATION_PENDING');
  let paymentRows = await rows(pool,'SELECT id FROM customer_payments WHERE business_id = ? AND sale_id = ? AND payment_method = \'CARD\'',[business,firstSale.id]);
  let movementRows = await rows(pool,'SELECT id FROM cash_movements WHERE business_id = ? AND customer_payment_id = ?',[business,String(paymentRows[0].id)]);
  const cardConfirm = await admin.request('/cash/payments/' + movementRows[0].id + '/confirm','POST',{operationKey:randomUUID()}); assert.equal(cardConfirm.status,200); assert.equal(cardConfirm.data.payment.status,'POSTED'); assert.equal(cardConfirm.data.payment.invoiceNumber,firstSale.invoiceNumber);
  const paidStock=await admin.request('/products/'+product.id);
  assert.equal((await admin.request('/sales/'+firstSale.id+'/cancel','POST',{operationKey:randomUUID(),reason:'Crédito con abonos'})).data.error.code,'CREDIT_HAS_PAYMENTS');
  assert.equal((await admin.request('/products/'+product.id)).data.product.stock,paidStock.data.product.stock);
  pay = await admin.request('/receivables/' + firstSale.id + '/payments','POST',{operationKey:randomUUID(),amount:'5.00',paymentMethod:'TRANSFER'}); assert.equal(pay.data.payment.status,'PENDING');
  paymentRows = await rows(pool,'SELECT id FROM customer_payments WHERE business_id = ? AND sale_id = ? AND payment_method = \'TRANSFER\'',[business,firstSale.id]);
  movementRows = await rows(pool,'SELECT id FROM cash_movements WHERE business_id = ? AND customer_payment_id = ?',[business,String(paymentRows[0].id)]);
  assert.equal((await admin.request('/cash/payments/' + movementRows[0].id + '/confirm','POST',{operationKey:randomUUID()})).data.payment.status,'POSTED');
  invoice = (await admin.request('/receivables?limit=100')).data.receivables.find(item => item.id === firstSale.id); assert.equal(invoice.status,'PAID'); assert.equal(invoice.balance,'0.00');
  const another = await admin.request('/clients','POST',newClient('Other ' + randomUUID().slice(0,8),'100.00')); assert.equal(another.status,201);
  const otherSale = await sale(another.data.client.id); assert.equal(otherSale.status,201);
  const statement = await admin.request('/clients/' + first.id + '/statement?limit=100&offset=0'); assert.equal(statement.data.invoices.length,1); assert.equal(statement.data.invoices[0].id,firstSale.id);
  const nextSaleResponse = await sale(first.id); assert.equal(nextSaleResponse.status,201); const nextSale = nextSaleResponse.data.sale;
  const overLimitQuote = await admin.request('/sales/quote','POST',creditCart(first.id,{items:[{productId:product.id,quantity:'0.001'}]})); assert.equal(overLimitQuote.status,409); assert.equal(overLimitQuote.data.error.code,'CREDIT_LIMIT_EXCEEDED');
  pay = await admin.request('/receivables/' + nextSale.id + '/payments','POST',{operationKey:randomUUID(),amount:'1.00',paymentMethod:'CARD'}); assert.equal(pay.status,201);
  paymentRows = await rows(pool,'SELECT id FROM customer_payments WHERE business_id = ? AND sale_id = ? AND payment_method = \'CARD\'',[business,nextSale.id]);
  movementRows = await rows(pool,'SELECT id FROM cash_movements WHERE business_id = ? AND customer_payment_id = ?',[business,String(paymentRows[0].id)]);
  cash = (await admin.request('/cash/current?full=true')).data.cash;
  await admin.request('/cash/sessions/' + cash.id + '/close','POST',{operationKey:randomUUID(),countedAmount:cash.expectedAmount});
  assert.equal((await admin.request('/receivables/' + nextSale.id + '/payments','POST',{operationKey:randomUUID(),amount:'1.00',paymentMethod:'CASH'})).data.error.code,'CASH_CLOSED');
  assert.equal((await admin.request('/cash/payments/' + movementRows[0].id + '/confirm','POST',{operationKey:randomUUID()})).data.payment.status,'POSTED');
  await admin.request('/cash/sessions','POST',{operationKey:randomUUID(),openingAmount:'0.00'});
  assert.equal((await admin.request('/clients/' + first.id,'PATCH',{creditLimit:'100.00'})).status,200);
  cash = (await admin.request('/cash/current?full=true')).data.cash;
  await admin.request('/cash/sessions/' + cash.id + '/close','POST',{operationKey:randomUUID(),countedAmount:cash.expectedAmount});
  await admin.request('/business-settings/sales-flow','PUT',{salesFlow:'CENTRALIZED'});
  const newCash = await admin.request('/cash/sessions','POST',{operationKey:randomUUID(),openingAmount:'0.00'}); assert.equal(newCash.status,201);
  const beforeOrderStock = (await admin.request('/products/' + product.id)).data.product.stock, beforeOrderSales = await count('sales'), beforeOrderCash = (await admin.request('/cash/current?full=true')).data.cash.expectedAmount;
  const orderData = {items:[{productId:product.id,quantity:'1.000'}],priceType:'RETAIL',discountPercent:'0',clientId:first.id,detail:'Credit order',operationKey:randomUUID()};
  const orderResponse = await admin.request('/sales/orders','POST',orderData); assert.equal(orderResponse.status,201); assert.equal(orderResponse.data.order.clientId,first.id);
  assert.equal((await admin.request('/products/' + product.id)).data.product.stock,beforeOrderStock); assert.equal(await count('sales'),beforeOrderSales);
  const orderId = orderResponse.data.order.id, orderQuote = await admin.request('/cash/orders/' + orderId + '/quote','POST',{paymentMethod:'CREDIT'}); assert.equal(orderQuote.status,200); assert.equal(orderQuote.data.quote.clientId,first.id);
  const charged = await admin.request('/cash/orders/' + orderId + '/charge','POST',{operationKey:randomUUID(),quoteToken:orderQuote.data.quote.quoteToken,paymentMethod:'CREDIT',cashReceived:null});
  assert.equal(charged.status,201); assert.equal(charged.data.sale.paymentMethod,'CREDIT'); assert.equal(charged.data.order.status,'COMPLETED');
  assert.equal((await admin.request('/products/' + product.id)).data.product.stock,'96.000'); assert.equal((await admin.request('/cash/current?full=true')).data.cash.expectedAmount,beforeOrderCash);
  assert.equal((await admin.request('/cash/overview')).data.overview.pendingOrders.length,0);
  const beforeCreditCancelStock=Number((await admin.request('/products/'+product.id)).data.product.stock), beforeCreditCancelCash=await count('cash_movements');
  const beforeStatement=(await admin.request('/clients/'+first.id+'/statement?limit=100&offset=0')).data;
  const creditCancel=await admin.request('/sales/'+charged.data.sale.id+'/cancel','POST',{operationKey:randomUUID(),reason:'Crédito sin abonos'});
  assert.equal(creditCancel.status,200);assert.equal(creditCancel.data.sale.status,'CANCELLED');assert.equal(creditCancel.data.sale.paymentMethod,'CREDIT');
  assert.equal(Number((await admin.request('/products/'+product.id)).data.product.stock),beforeCreditCancelStock+1);assert.equal(await count('cash_movements'),beforeCreditCancelCash);
  const afterStatement=(await admin.request('/clients/'+first.id+'/statement?limit=100&offset=0')).data;
  assert.equal(afterStatement.client.debt,(Number(beforeStatement.client.debt)-Number(charged.data.sale.total)).toFixed(2));
  assert.equal(afterStatement.invoices.find(item=>item.id===charged.data.sale.id).status,'CANCELLED');
  assert.equal((await admin.request('/sales/'+charged.data.sale.id+'/cancel','POST',{operationKey:randomUUID(),reason:'Segundo intento'})).data.error.code,'SALE_CANCELLED');
  assert.equal(Number((await admin.request('/products/'+product.id)).data.product.stock),beforeCreditCancelStock+1);
});
